# /// script
# requires-python = ">=3.12"
# dependencies = ["pillow>=10", "potracer>=0.0.4", "numpy>=1.26", "scipy>=1.11"]
# ///
"""Regenerates web/src/lib/map/vessels/class-icons.ts from WSDOT's official
per-class profile drawings (URLs live in the exploration samples).

Pipeline per class: download drawing -> masks (solid silhouette via
flood-fill; small interior openings = glass; WSF-green trim; dark hull) ->
potrace each -> layered SVG body using the MAP'S EXISTING token classes
(hull / win / cabin / keel), so day-dusk-night theming - including the
dusk lantern windows - costs nothing.

Run: uv run tools/vessel-icons/build_icons.py
"""

import json
import pathlib
import tempfile
import urllib.request

import numpy as np
import potrace
from PIL import Image
from scipy.ndimage import binary_fill_holes, label

ROOT = pathlib.Path(__file__).resolve().parents[2]
SAMPLES = ROOT / "api-exploration-wsdot-ferries/samples/vessels_vesselverbose.json"
OUT = ROOT / "web/src/lib/map/vessels/class-icons.ts"

FEET = {
    "Jumbo Mark II": 460,
    "Jumbo": 440,
    "Super": 382,
    "Olympic": 362,
    "Issaquah": 328,
    "Evergreen State": 310,
    "Kwa-di Tabil": 274,
}


def trace_d(mask: np.ndarray, turd: int, tol: float = 0.5) -> str:
    path = potrace.Bitmap(~mask).trace(turdsize=turd, alphamax=1.0, opticurve=1, opttolerance=tol)
    parts = []
    for curve in path:
        pt = curve.start_point
        d = f"M{pt.x:.1f} {pt.y:.1f}"
        for seg in curve.segments:
            if seg.is_corner:
                d += f"L{seg.c.x:.1f} {seg.c.y:.1f}L{seg.end_point.x:.1f} {seg.end_point.y:.1f}"
            else:
                d += (
                    f"C{seg.c1.x:.1f} {seg.c1.y:.1f} {seg.c2.x:.1f} {seg.c2.y:.1f} "
                    f"{seg.end_point.x:.1f} {seg.end_point.y:.1f}"
                )
        parts.append(d + "Z")
    return "".join(parts)


def build(drawing: pathlib.Path) -> tuple[str, str, float]:
    img = Image.open(drawing).convert("RGB")
    a = np.asarray(img).astype(int)
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    ship = ~((r > 235) & (g > 235) & (b > 235))
    filled = binary_fill_holes(ship)
    dark = (r < 90) & (g < 90) & (b < 90)
    green = (g > r + 18) & (g > b + 8) & (g > 55) & ~dark

    interior = filled & ~ship
    labels, n = label(interior)
    glass = np.zeros_like(interior)
    if n:
        sizes = np.bincount(labels.ravel())
        keep = np.zeros_like(sizes, dtype=bool)
        keep[1:] = sizes[1:] <= max(40, int(filled.sum()) * 0.004)
        glass = keep[labels]

    ys, xs = np.where(filled)
    x0, x1, y0, y1 = xs.min(), xs.max(), ys.min(), ys.max()
    body = (
        f'<path class="hull" d="{trace_d(filled, 25)}"/>'
        f'<path class="win" d="{trace_d(glass, 6)}"/>'
        f'<path class="cabin" d="{trace_d(green, 10)}"/>'
        f'<path class="keel" d="{trace_d(dark, 14)}"/>'
    )
    view_box = f"{x0} {y0} {int(x1 - x0 + 1)} {int(y1 - y0 + 1)}"
    aspect = float(y1 - y0 + 1) / float(x1 - x0 + 1)
    return body, view_box, aspect


def main() -> None:
    rows = json.loads(SAMPLES.read_text())
    drawings = {}
    for row in rows:
        c = row["Class"]
        drawings.setdefault(c["PublicDisplayName"], c["DrawingImg"])

    entries = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, feet in FEET.items():
            url = drawings[name]
            dest = pathlib.Path(tmp) / f"{name}.gif"
            urllib.request.urlretrieve(url, dest)
            body, view_box, aspect = build(dest)
            entries.append((name, feet, view_box, aspect, body))
            print(f"{name:16} {len(body) / 1024:5.1f} KB")

    ts = [
        "// GENERATED by tools/vessel-icons/build_icons.py - do not hand-edit.",
        "// Vector-traced from WSDOT's official class profile drawings; layer",
        "// classes (hull/win/cabin/keel) ride the existing mode tokens, so the",
        "// dusk lantern windows work per class for free.",
        "",
        "export interface ClassIcon {",
        "  feet: number;",
        "  viewBox: string;",
        "  aspect: number;",
        "  body: string;",
        "}",
        "",
        "export const CLASS_ICONS: Record<string, ClassIcon> = {",
    ]
    for name, feet, view_box, aspect, body in entries:
        ts.append(
            f'  "{name}": {{ feet: {feet}, viewBox: "{view_box}", '
            f"aspect: {aspect:.4f}, body: {json.dumps(body)} }},"
        )
    ts += [
        "};",
        "",
        "// Middle-of-fleet fallback for unknown classes (new boats, missing dims).",
        'export const DEFAULT_CLASS = "Issaquah";',
        "",
        "export function classIcon(className: string | undefined | null): ClassIcon {",
        '  return CLASS_ICONS[className ?? ""] ?? CLASS_ICONS[DEFAULT_CLASS]!;',
        "}",
        "",
        "export const REFERENCE_FEET = 460; // Jumbo Mark II - the width anchor",
        "",
        "export function classSvg(icon: ClassIcon): string {",
        "  return (",
        '    `<svg viewBox="${icon.viewBox}" preserveAspectRatio="xMidYMax meet" ` +',
        '    \'xmlns="http://www.w3.org/2000/svg" aria-hidden="true">\' + icon.body + "</svg>"',
        "  );",
        "}",
        "",
    ]
    OUT.write_text("\n".join(ts))
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
